#!/bin/bash

OUT_DIR="generated-scala-output"
echo "Removing generated .stg.fs files & scala-output..."
rm -- StgScala/*.stg.fs
#rm -r $OUT_DIR

dotnet build asn1scc

echo "Generating new .stg.fs files..."
cd StgScala && dotnet ../parseStg2/bin/Debug/net9.0/parseStg2.dll backends.xml 3 && cd ..

echo "Running Asn1SCC Compiler for Scala..."
./asn1scc/bin/Debug/net9.0/asn1scc \
-Scala --acn-enc -atc --field-prefix AUTO --type-prefix T \
-o $OUT_DIR \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/additional-test-cases/NULLTERMINATED.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/ccsds/PacketTypes.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/ccsds/TC-Packet.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/ccsds/TC-Payload.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/ApplicationProcess.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/ApplicationProcessUser.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/BasicTypes.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/DiagnosticParameterReportStructure.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/Dummy.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/EventDefinition.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/ExecutionStep.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/FilePath.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/HousekeepingParameterReportStructure.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/MessageType.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/Parameter.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/Request.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/SpacecraftTimeReferenceStatus.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/TimeWindow.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/ErrorCodes.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-10.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-2.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-3.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-4.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-5.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-6.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-7.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-8.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/VerificationRequest.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/LogicalDevice.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PhysicalDevice.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-10.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-11.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-12.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-2.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-4.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-5.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-6.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-7.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-8.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-9.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/Registers.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/Transaction.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/CollectionInterval.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/ParameterFunctionalReportingDefinition.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/ParameterReportingEntries.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/ParameterReportStructureType.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PeriodicGenerationActionStatus.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PeriodicGenerationProperties.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-10.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-11.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-12.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-2.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-25.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-26.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-27.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-28.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-29.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-3.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-30.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-31.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-32.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-33.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-34.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-35.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-36.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-37.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-38.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-39.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-4.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-40.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-41.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-42.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-43.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-44.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-5.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-6.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-7.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-8.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-9.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/Intervals.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/ParameterStatisticsDefinitions.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-2.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-3.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-4.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-5.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-6.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-7.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-8.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-9.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-2.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-3.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-4.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-5.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-6.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-7.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-8.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/Data.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/Memory.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-10.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-11.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-12.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-13.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-14.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-15.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-16.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-17.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-18.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-19.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-2.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-20.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-21.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-22.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-3.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-4.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-5.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-6.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-7.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-8.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-9.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/RawMemory.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/StructuredMemory.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-08/PUS-8-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/PUS-9-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/PUS-9-2.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/PUS-9-3.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/RateExponentialValue.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/Group.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-10.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-11.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-12.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-13.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-14.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-15.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-16.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-17.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-18.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-19.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-2.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-20.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-21.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-22.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-23.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-24.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-25.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-26.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-27.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-3.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-4.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-5.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-6.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-7.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-8.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-9.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/SubSchedule.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/CheckValidityCondition.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/FMON.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/ParameterMonitoringDefinition.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PMON.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PMON-FailingNumber.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-1.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-10.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-13.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-14.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-15.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-16.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-17.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-18.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-19.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-2.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-20.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-21.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-22.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-23.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-24.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-25.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-26.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-27.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-28.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-3.asn1 \
./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-4.asn1