version: 2
jobs:
  build:
    machine: 
      image: ubuntu-2404:edge
      docker_layer_caching: false
    steps:
      - checkout
      - run:
          command: docker build -t asn1scc .
      - run:
          command: docker run -it -v $(pwd):/root/asn1scc asn1scc /bin/bash -c 'cd /root/asn1scc ; ./circleci-build.sh'
    # The resource_class feature allows configuring CPU and RAM resources for each job. Different resource classes are available for different executors. https://circleci.com/docs/2.0/configuration-reference/#resourceclass   
    resource_class: large
