"""
ASN.1 Python Runtime Library

This module provides ASN.1-specific types and operations for Python code generation.
Generated by asn1scc - the ASN.1 compiler of the European Space Agency (ESA).
"""

from .asn1_types import (
    Asn1Base, Asn1Boolean, NullType,

    # Constraint Validation
    Asn1ConstraintValidResult,

    # Error handling
    Asn1Exception, Asn1InvalidValueException, Asn1OverflowException, Asn1ValueOutOfRangeException, Asn1ValueUnexpectedEndOfDataException,
    
    # Testcase Errors
    Asn1TestcaseError, Asn1TestcaseEncodeFailedError, Asn1TestcaseDecodeFailedError, Asn1TestcaseConstraintFailedError, Asn1TestcaseDifferentResultError
)

from .bitstream import BitStream, BitStreamError

from .codec import (
    Codec, EncodeResult, DecodeResult, ErrorCode,
    ENCODE_OK, DECODE_OK, ERROR_INSUFFICIENT_DATA,
    ERROR_INVALID_VALUE, ERROR_CONSTRAINT_VIOLATION,
)

from .codec_uper import UPEREncoder, UPERDecoder

from .acn_encoder import ACNEncoder
from .acn_decoder import ACNDecoder

__version__ = "1.0.0"
__author__ = "ASN.1 SCC Team"
__description__ = "ASN.1 runtime library for Python"

__all__ = [
    # Base Class
    "Asn1Base",

    "Asn1Boolean", "NullType",

    # Constraint Validation
    "Asn1ConstraintValidResult",

    # Errors
    "Asn1Exception", "Asn1InvalidValueException", "Asn1OverflowException", "Asn1ValueOutOfRangeException", "Asn1ValueUnexpectedEndOfDataException",

    # Testcase Errors
    "Asn1TestcaseError", "Asn1TestcaseEncodeFailedError", "Asn1TestcaseDecodeFailedError", "Asn1TestcaseConstraintFailedError", "Asn1TestcaseDifferentResultError",

    # Bitstream
    "BitStream", "BitStreamError",

    # Codecs
    "Codec", "EncodeResult", "DecodeResult", "ErrorCode",
    "UPEREncoder", "UPERDecoder", "ACNEncoder", "ACNDecoder",

    # Constants
    "ENCODE_OK", "DECODE_OK", "ERROR_INSUFFICIENT_DATA",
    "ERROR_INVALID_VALUE", "ERROR_CONSTRAINT_VIOLATION",
]