"""
ASN.1 Python Runtime Library

This module provides ASN.1-specific types and operations for Python code generation.
Generated by asn1scc - the ASN.1 compiler of the European Space Agency (ESA).
"""

# from .bitstream import BitStream, BitStreamError

# from .verification import (
#     byte_set_bit,
#     byteseq_set_bit,
# )

# from .codec import Codec

__version__ = "1.0.0"
__author__ = "ASN.1 SCC Team"
__description__ = "ASN.1 runtime library for Python"